### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by Jobians** [yarkincaner/reddit-clone#1]
Please why I can't post image, also when I logged in only my feed is showing

**Comment by Tanisha-s-ingh** [comment]
Sometimes apps or websites just have weird temporary issues things like posting images or loading pages can stop working.
What you can do is  Try refreshing the page, logging out and back in, or clearing your browser cache. If you're on your phone, maybe try a different browser or device and see if that helps.

**Comment by Jobians** [comment]
@Tanisha-s-ingh so users will keep doing it?

**Comment by Jobians** [comment]
Couldn’t upload image. Please try another.

**Comment by yarkincaner** [comment]
I assume that the problem you are facing is probably caused by the size of the image you are trying to upload. The current limit on image upload function is 4 megabytes. Now implemented an image compressor and will merge to main. You can try again when the newer version is deployed. If your issue continues, you can create a new one.

**Comment by Jobians** [comment]
Why only community search you implement

**Comment by yarkincaner** [comment]
When a user logs in, they usually want to see their custom feed with their followed topics. I can create a route "r/all" like on Reddit that will only show the GeneralFeed component, but since this is only a portfolio project, I don't plan to do it.

**Comment by Jobians** [comment]
Add new features update this script

**Comment by Tanisha-s-ingh** [comment]
@Jobians sometimes i uninstall the app and re install it kinda works sometimes

**Comment by Jobians** [comment]
Any updates?
